# Generated by Django 4.0.3 on 2022-03-07 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vocab',
            old_name='keyword',
            new_name='vocab',
        ),
    ]
