# Generated by Django 4.0.3 on 2022-03-07 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vocab', '0002_rename_keyword_vocab_vocab'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vocab',
            name='vocab',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
